file:
  upload: /website/upload/


spring:
  datasource:
    username: root
    password: 51asp.netandjsp
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.159.48:3306/blog?characterEncoding=UTF-8
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/,classpath:/public/,file:/website/upload/
  jackson:
    date-format: yyyy-MM-dd
  profiles:
    active: dev




mybatis-plus:
  type-aliases-package: com.imodou.blog.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: true
server:
  port: 80



