

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/,classpath:/public/,file:d:\upload\


mybatis-plus:
  type-aliases-package: com.imodou.blog.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: true
server:
  port: 80

